### ISSUE TITLE
Broken images in RSS feed

### ISSUE THREAD

**Issue by VerifiedJoseph** [subract/subract.github.io#1]
I subscribed to your website's RSS after reading the post about Dashy and noticed that the images are broken.

![public](https://github.com/subract/subract.github.io/assets/20118140/04dd8782-f8d2-452a-8364-537bf7ddbe39)
(from my feed reader)

```HTML
 <p><img loading="lazy" src="dashy-demo.png#center" alt="Dashy demo screenshot" /> </p>
```
(from the feed)

**Comment by subract** [comment]
Thanks for the report. I'll have to convince Hugo to generate absolute URLs to those images.

**Comment by subract** [comment]
Should be working now. My feed reader (Miniflux) correctly resolved the original relative URLs (hence why I didn't notice the issue in the first place), so let me know if you encounter any more issues.

**Comment by VerifiedJoseph** [comment]
it's fixed. 👍
